# Generated by Django 5.2.14 on 2026-06-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_habit_logs_habit_date_idx_habit_logs_habit_i_5cd283_idx_and_more'),
        ('notifications', '0001_initial'),
        ('tasks', '0002_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task'),
        ),
    ]
