# Generated by Django 5.2.14 on 2026-06-06 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='challenges.challenge'),
        ),
    ]
