# Generated by Django 5.2.14 on 2026-06-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('habits', '0002_habitlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='habitlog',
            new_name='habit_logs_habit_i_5cd283_idx',
            old_name='habit_logs_habit_date_idx',
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='categories.category'),
        ),
    ]
