# Generated by Django 5.2.14 on 2026-06-28 08:23

from django.db import migrations, models


def migrate_habit_statuses(apps, schema_editor):
    Habit = apps.get_model("habits", "Habit")
    Habit.objects.exclude(status="DELETED").update(status="ACTIVE")


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_habit_logs_habit_date_idx_habit_logs_habit_i_5cd283_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_habit_statuses, migrations.RunPython.noop),
        migrations.AddField(
            model_name='habitlog',
            name='action',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('SKIPPED', 'Skipped')], default='CHECKED_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
    ]
