# Generated by Django 5.2.14 on 2026-06-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0002_tasklog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_task_id_43fe97_idx',
            old_name='task_logs_task_created_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='categories.category'),
        ),
    ]
