# Generated by Django 5.2.14 on 2026-06-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_succeeded', models.PositiveIntegerField(default=0)),
                ('time_failed', models.PositiveIntegerField(default=0)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_tracking',
            },
        ),
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_succeeded', models.PositiveIntegerField(default=0)),
                ('time_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='tasks.task')),
            ],
            options={
                'db_table': 'task_tracking',
            },
        ),
    ]
